### ISSUE TITLE
命令无返回&字数过多时不发送消息

### ISSUE THREAD

**Issue by ABKQPO** [IllTamer/infinitebot3#12]
可否将字数过多的返回分段合并转发发送，或者以图片形式发送
无返回时可发送自定义的信息

**Comment by ABKQPO** [comment]
另外能否添加屏蔽指定QQ用户的消息

**Comment by IllTamer** [comment]
- 长消息拆分合并发送 Fixed by https://github.com/IllTamer/infinitebot3/commit/d8ccc61c0f69b9492afd859bbfe809a6ac90a5b8
- 其他功能待后续本体框架更新
