### ISSUE TITLE
BasicManager附属无法绑定QQ

### ISSUE THREAD

**Issue by 3328429240** [IllTamer/infinitebot3#6]
玩家在群内可以正常发起对游戏内玩家的绑定请求，但是游戏内发送确认绑定并不可以成功绑定（输入后没任何提示，并且被转发到了群里面）
再次查询还是显示未绑定
如图
![86NXZ4H6)9}%H}KZ4GWEK}K](https://user-images.githubusercontent.com/43557921/201474064-bd477402-b24b-4a6a-b61f-2e1bf67207fc.png)

**Comment by IllTamer** [comment]
> **附属问题请提交至附属仓库**

已修复，请下载最新版本 https://github.com/IllTamer/infinitebot3/releases/tag/v3.1.4
